### ISSUE TITLE
undefined method

### ISSUE THREAD

**Issue by Nickcarter74** [tkock/flowchartwiki#5]
Hello, on a fresh installation, i tried to install this extension. i have the following error when i am trying to save a page.

[298bf656cd9148c88c5548ae] /wikirtc/index.php?title=Test1&action=submit Error from line 88 of /var/www/html/wikirtc/extensions/flowchartwiki/linktypes.php: Call to undefined method Revision::getText()

Backtrace:

#0 /var/www/html/wikirtc/includes/Hooks.php(186): fchw_UpdateLinks(LinksUpdate)
#1 /var/www/html/wikirtc/includes/deferred/LinksUpdate.php(160): Hooks::run(string, array)
#2 /var/www/html/wikirtc/includes/content/AbstractContent.php(234): LinksUpdate->__construct(Title, ParserOutput, boolean)
#3 /var/www/html/wikirtc/includes/page/WikiPage.php(2168): AbstractContent->getSecondaryDataUpdates(Title, NULL, boolean, ParserOutput)
#4 /var/www/html/wikirtc/includes/page/WikiPage.php(1913): WikiPage->doEditUpdates(Revision, User, array)
#5 [internal function]: WikiPage->{closure}(Wikimedia\Rdbms\DatabaseMysqli, string)
#6 /var/www/html/wikirtc/includes/libs/rdbms/database/Database.php(2693): call_user_func_array(Closure, array)
#7 /var/www/html/wikirtc/includes/deferred/AtomicSectionUpdate.php(35): Wikimedia\Rdbms\Database->doAtomicSection(string, Closure)
#8 /var/www/html/wikirtc/includes/deferred/DeferredUpdates.php(257): AtomicSectionUpdate->doUpdate()
#9 /var/www/html/wikirtc/includes/deferred/DeferredUpdates.php(210): DeferredUpdates::runUpdate(AtomicSectionUpdate, Wikimedia\Rdbms\LBFactorySimple, string, integer)
#10 /var/www/html/wikirtc/includes/deferred/DeferredUpdates.php(127): DeferredUpdates::execute(array, string, integer)
#11 /var/www/html/wikirtc/includes/MediaWiki.php(603): DeferredUpdates::doUpdates(string, integer)
#12 /var/www/html/wikirtc/includes/MediaWiki.php(572): MediaWiki::preOutputCommit(RequestContext, Closure)
#13 /var/www/html/wikirtc/includes/MediaWiki.php(878): MediaWiki->doPreOutputCommit(Closure)
#14 /var/www/html/wikirtc/includes/MediaWiki.php(523): MediaWiki->main()
#15 /var/www/html/wikirtc/index.php(43): MediaWiki->run()
#16 {main}

`

MediaWiki | 1.29.1
PHP | 7.0.22-0ubuntu0.16.04.1 (apache2handler)
MySQL | 5.7.19-0ubuntu0.16.04.1
FlowchartWiki | 1.2.4

**Comment by tkock** [comment]
Thanks for reporting! 
I will have a look at it over the weekend.

**Comment by Nickcarter74** [comment]
just for debugging: if i push twice the browser back button (error page-->edit page---> view page) , i receive a "successful saved" message,

**Comment by tkock** [comment]
I have pushed changes to branch "deprecated-revision-gettext" (https://github.com/tkock/flowchartwiki/tree/deprecated-revision-gettext).
Could you please have a go at it and let me know?

**Comment by Nickcarter74** [comment]
i will try it soon.
